word_list = ['abruptly', 'absurd', 'abyss', 'affix', 'askew', 'avenue', 'awkward', 'axiom', 'azure', 'bagpipes',
             'bandwagon', 'banjo', 'bayou', 'beekeeper', 'bikini', 'blitz', 'blizzard', 'boggle', 'bookworm', 'boxcar',
             'boxful', 'buckaroo', 'buffalo', 'buffoon', 'buxom', 'buzzard', 'buzzing', 'buzzwords', 'caliph', 'cobweb',
             'cockiness', 'croquet', 'crypt', 'curacao', 'cycle', 'daiquiri', 'dirndl', 'disavow', 'dizzying', 'duplex',
             'dwarves', 'embezzle', 'equip', 'espionage', 'euouae', 'exodus', 'faking', 'fishhook', 'fixable', 'fjord',
             'flapjack', 'flopping', 'fluffiness', 'flyby', 'foxglove', 'frazzled', 'frizzled', 'fuchsia', 'funny',
             'gabby', 'galaxy', 'galvanize', 'gazebo', 'giaour', 'gizmo', 'glowworm', 'glyph', 'gnarly', 'gnostic',
             'gossip', 'grogginess', 'haiku', 'haphazard', 'hyphen', 'iatrogenic', 'icebox', 'injury', 'ivory', 'ivy',
             'jackpot', 'jaundice', 'jawbreaker', 'jaywalk', 'jazziest', 'jazzy', 'jelly', 'jigsaw', 'jinx', 'jiujitsu',
             'jockey', 'jogging', 'joking', 'jovial', 'joyful', 'juicy', 'jukebox', 'jumbo', 'kayak', 'kazoo',
             'keyhole', 'khaki', 'kilobyte', 'kiosk', 'kitsch', 'kiwifruit', 'klutz', 'knapsack', 'larynx', 'lengths',
             'lucky', 'luxury', 'lymph', 'marquis', 'matrix', 'megahertz', 'microwave', 'mnemonic', 'mystify',
             'naphtha', 'nightclub', 'nowadays', 'numbskull', 'nymph', 'onyx', 'ovary', 'oxidize', 'oxygen', 'pajama',
             'peekaboo', 'phlegm', 'pixel', 'pizazz', 'pneumonia', 'polka', 'pshaw', 'psyche', 'puppy', 'puzzling',
             'quartz', 'queue', 'quips', 'quixotic', 'quiz', 'quizzes', 'quorum', 'razzmatazz', 'rhubarb', 'rhythm',
             'rickshaw', 'schnapps', 'scratch', 'shiv', 'snazzy', 'sphinx', 'spritz', 'squawk', 'staff', 'strength',
             'strengths', 'stretch', 'stronghold', 'stymied', 'subway', 'swivel', 'syndrome', 'thriftless',
             'thumbscrew', 'topaz', 'transcript', 'transgress', 'transplant', 'triphthong', 'twelfth', 'twelfths',
             'unknown', 'unworthy', 'unzip', 'uptown', 'vaporize', 'vixen', 'vodka', 'voodoo', 'vortex', 'voyeurism',
             'walkway', 'waltz', 'wave', 'wavy', 'waxy', 'wellspring', 'wheezy', 'whiskey', 'whizzing', 'whomever',
             'wimpy', 'witchcraft', 'wizard', 'woozy', 'wristwatch', 'wyvern', 'xylophone', 'yachtsman', 'yippee',
             'yoked', 'youthful', 'yummy', 'zephyr', 'zigzag', 'zigzagging', 'zilch', 'zipper', 'zodiac', 'zombie']

lista_palavras = ['bruscamente', 'absurdo', 'abismo', 'afixar', 'torto', 'avenida', 'desajeitado', 'axioma',
                  'azul-celeste', 'gaita-de-fole','modismo', 'banjo', 'baixio', 'apicultor', 'biquíni', 'blitz',
                  'nevasca', 'atordoar', 'rato de biblioteca', 'vagão de carga', 'caixa cheia', 'peão', 'búfalo',
                  'bufão', 'volumoso', 'abutre', 'zumbido', 'palavras da moda', 'califa', 'teia de aranha','arrogância',
                  'croquet', 'cripta', 'curaçau', 'ciclo', 'daiquiri', 'vestido típico alemão', 'desavow', 'tontura',
                  'duplex', 'anões', 'desviar dinheiro', 'equipar', 'espionagem', 'euouae', 'êxodo', 'fazendo de conta',
                  'anzol', 'corrigível', 'fiorde', 'panqueca', 'agitar', 'fofura', 'passagem rápida', 'dedaleira',
                  'exausto', 'encaracolado', 'fúcsia', 'engraçado', 'tagarela', 'galáxia', 'galvanizar', 'coreto',
                  'herege', 'gadget', 'bicho de luz', 'glifo', 'exótico', 'gnóstico', 'fofoca', 'sonolência', 'haicai',
                  'aleatório', 'hífen', 'iatrogênico', 'geladeira', 'lesão', 'marfim', 'hera', 'prêmio máximo',
                  'icterícia', 'quebra-queixo', 'atravessar fora da faixa', 'mais jazzy', 'jazzy', 'geleia',
                  'quebra-cabeça', 'azar', 'jiujitsu', 'jóquei', 'corrida', 'brincalhão', 'jovial', 'alegre',
                  'suculento', 'jukebox', 'gigante', 'caiaque', 'zabumba', 'fechadura', 'cáqui', 'quilobyte',
                  'quiosque', 'cafonice', 'quiwi', 'desastrado', 'mochila', 'laringe', 'comprimentos', 'sortudo',
                  'luxo', 'linfa', 'marquês', 'matriz', 'megahertz', 'micro-ondas', 'mnemônico', 'misterioso', 'nafta',
                  'boate', 'hoje em dia', 'pateta', 'ninfa', 'ônix', 'ovário', 'oxidar', 'oxigênio', 'pijama', 'bubi',
                  'catarro', 'pixel', 'pizazz', 'pneumonia', 'polca', 'pshaw', 'psique', 'filhote', 'intrigante',
                  'quartzo', 'fila', 'gracejos', 'quixotesco', 'questionário', 'questionários', 'quórum',
                  'alegria contagiante', 'ruibarbo', 'ritmo', 'riquixá', 'schnapps', 'arranhão', 'caco', 'chique',
                  'esfinge', 'spritz', 'grito', 'equipe', 'força', 'pontos fortes', 'alongamento', 'fortaleza',
                  'embaraçado', 'metrô', 'girar', 'síndrome', 'desperdiçador', 'parafuso de polegar', 'topázio',
                  'transcrição', 'transgredir', 'transplantar', 'trifongo', 'décimo-segundo', 'décimo-segundos',
                  'desconhecido', 'indigno', 'descomprimir', 'zona nobre', 'vaporizar', 'raposa', 'vodka', 'vodu',
                  'vórtice', 'voyeurismo', 'calçadão', 'valsar', 'onda', 'ondulado', 'ceroso', 'nascente', 'ofegante',
                  'uísque', 'zumbido', 'quem quer que seja', 'fraco', 'bruxaria', 'mágico', 'tonto', 'relógio de pulso',
                  'dragão', 'xilofone', 'iemanjá', 'yippee', 'amarrado', 'jovial', 'gostoso', 'zéfiro', 'ziguezague',
                  'zigzagueando', 'nada', 'zíper', 'zodíaco', 'zumbi']
